package service

import (
	"io"
	"net/http"
	"strings"

	"github.com/bytedance/sonic"
	"github.com/jz0ojiang/go-maimai-player-counter/conf"
)

// Generated by https://quicktype.io

type TurnstileResponse struct {
	Success     bool          `json:"success"`
	ErrorCodes  []interface{} `json:"error-codes"`
	ChallengeTs string        `json:"challenge_ts"`
	Hostname    string        `json:"hostname"`
}

func VerifyTurnstile(turnstileResponse string) bool {
	payload := strings.NewReader("response=" + turnstileResponse + "&secret=" + conf.GetConfig().TurnstileSecret)
	response, err := http.Post("https://challenges.cloudflare.com/turnstile/v0/siteverify", "application/x-www-form-urlencoded", payload)
	if err != nil {
		return false
	}
	defer response.Body.Close()
	body, err := io.ReadAll(response.Body)
	if err != nil {
		return false
	}
	var turnstileResponseStruct TurnstileResponse
	err = sonic.Unmarshal(body, &turnstileResponseStruct)
	if err != nil {
		return false
	}
	return turnstileResponseStruct.Success
}
